language: r
sudo : false
cache: packages


r:
  - release

r_packages:
  - R6
  - ParamHelpers
  - BBmisc
  - checkmate
  - smoof
  - knitr
  - rmarkdown
  - testthat
  - mlr
  - reshape2
  - ggplot2
  - dplyr
  - data.table

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::coveralls()'
